modAccessor {
    createTransformConfiguration(configurations.compileOnly)
    accessTransformerFiles = project.files('src/main/resources/META-INF/accesstransformer.cfg')
}

dependencies {
    compileOnly("org.jetbrains:annotations:26.0.1")

    // Mixin
    annotationProcessor('org.spongepowered:mixin:0.8.5:processor')
    annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0-rc.3")

    // JEI, EMI, Jade 优先EMI
    //modImplementation("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    //modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    modCompileOnly("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    modRuntimeOnly("dev.emi:emi-forge:${emi_version}+${minecraft_version}")
    modImplementation("curse.maven:tmrv-1194921:7259315")
    modImplementation("curse.maven:jade-324717:6855440")

    // GregTech and dependencies 兼容
    modCompileOnly("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtceu_version}:slim") { transitive = false }
    modRuntimeOnly("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtceu_version}:slim")
    modCompileOnly("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:${ldlib_version}"){ transitive = false }
    modRuntimeOnly("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:${ldlib_version}")

    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    modImplementation("dev.toma.configuration:configuration-forge-${minecraft_version}:${configuration_version}")

    // Curios
    modRuntimeOnly("top.theillusivec4.curios:curios-forge:${curios_version}")
    modCompileOnly("top.theillusivec4.curios:curios-forge:${curios_version}:api")
    modImplementation("curse.maven:cloth-config-348521:5729105")

    modImplementation("curse.maven:architectury-api-419699:5137938")

    //ae2
    accessCompileOnly(("appeng:appliedenergistics2-forge:${ae2_version}"))
    modImplementation("appeng:appliedenergistics2-forge:${ae2_version}")


    modImplementation("curse.maven:guideme-1173950:6679102")

    //eae 依赖这个
    modImplementation("curse.maven:glodium-957920:5226922")
    modImplementation("curse.maven:ex-pattern-provider-892005:7248944")

    //ae2wt 依赖这个
    modImplementation("curse.maven:applied-energistics-2-wireless-terminals-459929:7154316")

    //PCC 兼容
    modCompileOnly("curse.maven:programmed-circuit-card-1150540:7152160")
    modRuntimeOnly("curse.maven:programmed-circuit-card-1150540:7152160")


}